In [1]:
import meshio

In [2]:
mio_m = meshio.read("meshes/cube40_equi_grains8_gsize20.med", "med")

## Conversion to `gmsh`

In [3]:
mio_m.write("meshes/standard_mesh.msh", "gmsh")

WriteError: Specify entity information (gmsh:dim_tags in point_data) to deal with more than one cell type. 

In [4]:
mio_m.write("meshes/standard_mesh.msh", "gmsh22")

Warning: Appending zeros to replace the missing physical tag data.

Warning: Appending zeros to replace the missing geometrical tag data.

In [5]:
mio_new_gmsh = meshio.read("meshes/standard_mesh.msh")
mio_new_gmsh

Warning: The file contains tag data that couldn't be processed.

<meshio mesh object>
  Number of points: 53586
  Number of cells:
    line: 1681
    tetra: 311543
    triangle: 23546
  Point data: point_tags
  Cell data: gmsh:physical, gmsh:geometrical

In [6]:
import numpy as np

In [7]:
np.unique(mio_new_gmsh.cell_data_dict["gmsh:physical"]["tetra"])

array([0], dtype=int32)

> **NOTE:** No physical tags survived!

In [8]:
np.unique(mio_new_gmsh.cell_data_dict["gmsh:geometrical"]["tetra"])

array([0], dtype=int32)

## Conversion to `vtu`

In [9]:
mio_m.write("meshes/standard_mesh.vtu")

In [10]:
mio_new_vtu = meshio.read("meshes/standard_mesh.vtu")

### Comparing old and new mesh objects with `meshio`

In [11]:
mio_m

<meshio mesh object>
  Number of points: 53586
  Number of cells:
    line: 1681
    tetra: 311543
    triangle: 23546
  Point data: point_tags
  Cell data: cell_tags

In [12]:
mio_new_vtu

<meshio mesh object>
  Number of points: 53586
  Number of cells:
    line: 1681
    tetra: 311543
    triangle: 23546
  Point data: point_tags
  Cell data: cell_tags

In [13]:
mio_m.cell_tags

{np.int64(-6): ['1'],
 np.int64(-7): ['2'],
 np.int64(-8): ['3'],
 np.int64(-9): ['4'],
 np.int64(-10): ['5'],
 np.int64(-11): ['6'],
 np.int64(-12): ['7'],
 np.int64(-13): ['8'],
 np.int64(-14): ['9'],
 np.int64(-15): ['10'],
 np.int64(-16): ['11']}

In [14]:
mio_new_vtu.cell_tags

AttributeError: 'Mesh' object has no attribute 'cell_tags'

>**NOTE:** The "names" of the subregions are lost.

In [15]:
mio_new_vtu.cell_data_dict

{'cell_tags': {'line': array([0, 0, 0, ..., 0, 0, 0], shape=(1681,)),
  'tetra': array([-16, -16, -16, ...,  -6,  -6,  -6], shape=(311543,)),
  'triangle': array([0, 0, 0, ..., 0, 0, 0], shape=(23546,))}}

In [16]:
np.allclose(
    mio_m.cell_data_dict["cell_tags"]["tetra"],
    mio_new_vtu.cell_data_dict["cell_tags"]["tetra"]
)

True

In [17]:
np.allclose(
    mio_m.cell_data_dict["cell_tags"]["line"],
    mio_new_vtu.cell_data_dict["cell_tags"]["line"]
)

True

In [18]:
np.allclose(
    mio_m.cell_data_dict["cell_tags"]["triangle"],
    mio_new_vtu.cell_data_dict["cell_tags"]["triangle"]
)

True

In [19]:
np.unique(mio_new_vtu.cell_data_dict["cell_tags"]["tetra"])

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6])

In [20]:
mio_m.cell_tags

{np.int64(-6): ['1'],
 np.int64(-7): ['2'],
 np.int64(-8): ['3'],
 np.int64(-9): ['4'],
 np.int64(-10): ['5'],
 np.int64(-11): ['6'],
 np.int64(-12): ['7'],
 np.int64(-13): ['8'],
 np.int64(-14): ['9'],
 np.int64(-15): ['10'],
 np.int64(-16): ['11']}