In [1]:
import meshio

## Read Salome `msh` file

In [2]:
m_msh = meshio.read("meshes/test.msh")

In [3]:
m_msh

<meshio mesh object>
  Number of points: 11551
  Number of cells:
    line: 1372
    tetra: 66094
    triangle: 10802
  Point data: point_tags
  Cell data: cell_tags, gmsh:geometrical

In [8]:
import numpy as np

In [9]:
np.unique(m_msh.cell_data_dict["cell_tags"]["tetra"])

array([-20., -19., -18., -17., -16., -15., -14., -13., -12., -11., -10.,
        -9.,  -8.,  -7.,  -6.])

>**NOTE:** we have lost the subregion names, i.e., "1", "2", etc.

In [17]:
np.unique(m_msh.point_data["point_tags"])

array([0.])

In [19]:
m_msh.cell_data_dict["gmsh:geometrical"]

{'line': array([1, 1, 1, ..., 1, 1, 1], shape=(1372,)),
 'tetra': array([1, 1, 1, ..., 1, 1, 1], shape=(66094,)),
 'triangle': array([1, 1, 1, ..., 1, 1, 1], shape=(10802,))}

In [18]:
np.unique(m_msh.cell_data_dict["gmsh:geometrical"]["tetra"])

array([1])

## Read Salome `vtu` file

In [10]:
m_vtu = meshio.read("meshes/test.vtu")

In [11]:
m_vtu

<meshio mesh object>
  Number of points: 11551
  Number of cells:
    line: 1372
    tetra: 66094
    triangle: 10802
  Point data: point_tags
  Cell data: cell_tags

In [13]:
np.unique(m_vtu.cell_data_dict["cell_tags"]["tetra"])

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6])

>**Note:** same as the `msh` file!

In [16]:
np.unique(m_vtu.point_data["point_tags"])

array([0])